# Generated by Django 2.0.7 on 2018-10-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0002_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='reservations',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rezerwacje.Reservations'),
        ),
    ]
