# Generated by Django 2.0.7 on 2018-10-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0003_auto_20181023_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='reservations',
        ),
        migrations.AddField(
            model_name='reservations',
            name='rooms',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rezerwacje.Rooms'),
        ),
    ]
