# Generated by Django 2.0.7 on 2018-10-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0004_auto_20181023_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='rooms',
            new_name='room',
        ),
    ]
